import 'dotenv/config';
import { v4 as uuidv4 } from 'uuid';
import bcrypt from 'bcryptjs';
import { initializeDatabase, getDb, closeDatabase, dbRun, dbGet } from './index.js';

async function seed() {
  console.log('Starting database seed...');

  await initializeDatabase();

  // Create SuperAdmin user
  const superAdminId = uuidv4();
  const passwordHash = await bcrypt.hash('admin123', 12);

  const existingAdmin = await dbGet('SELECT id FROM users WHERE role = ?', ['SuperAdmin']);

  if (!existingAdmin) {
    await dbRun(
      `INSERT INTO users (id, username, password_hash, role, email, full_name, title) VALUES (?, 'admin', ?, 'SuperAdmin', 'admin@aptiv.local', 'System Administrator', 'IT Ops Lead')`,
      [superAdminId, passwordHash]
    );
    console.log('✓ SuperAdmin user created (username: admin, password: admin123)');
  } else {
    console.log('✓ SuperAdmin already exists, skipping');
  }

  const adminUser = await dbGet('SELECT TOP 1 id FROM users WHERE role = ?', ['SuperAdmin']) as any;
  const adminId = adminUser ? adminUser.id : superAdminId;

  // Create sample machines
  console.log('Checking machines...');
  const machines = [
    { hostname: 'APTIV-LPT-001', category: 'User', os: 'Windows 11 Pro', status: 'online', tags: ['finance', 'laptop'], ip: '10.0.1.15' },
    { hostname: 'APTIV-LPT-002', category: 'User', os: 'Windows 10 Enterprise', status: 'offline', tags: ['hr', 'laptop', 'legacy'], ip: '10.0.1.22' },
    { hostname: 'APTIV-WS-001', category: 'Shopfloor', os: 'Windows 10 IoT', status: 'online', tags: ['production', 'line-1'], ip: '10.0.5.101' },
    { hostname: 'APTIV-WS-002', category: 'Shopfloor', os: 'Windows 10 IoT', status: 'online', tags: ['production', 'line-1'], ip: '10.0.5.102' },
    { hostname: 'APTIV-SRV-DC01', category: 'Server', os: 'Windows Server 2022', status: 'online', tags: ['infrastructure', 'domain-controller', 'critical'], ip: '10.0.0.10' },
    { hostname: 'APTIV-SRV-APP01', category: 'Server', os: 'Ubuntu 22.04 LTS', status: 'online', tags: ['infrastructure', 'web-server'], ip: '10.0.0.20' },
    { hostname: 'APTIV-DESK-044', category: 'User', os: 'Windows 11 Pro', status: 'online', tags: ['engineering', 'cad'], ip: '10.0.2.55' },
    { hostname: 'APTIV-KIOSK-01', category: 'Kiosk', os: 'Windows 10 Enterprise', status: 'online', tags: ['lobby', 'visitor'], ip: '10.0.3.5' },
    { hostname: 'APTIV-LPT-099', category: 'User', os: 'macOS Sonoma', status: 'offline', tags: ['design', 'marketing'], ip: '10.0.2.200' },
    { hostname: 'APTIV-TEST-VM01', category: 'Server', os: 'Windows Server 2019', status: 'offline', tags: ['test', 'dev'], ip: '10.10.0.5' },
  ];

  for (const m of machines) {
    const existing = await dbGet('SELECT id FROM machines WHERE hostname = ?', [m.hostname]);

    if (!existing) {
      const id = uuidv4();
      await dbRun('INSERT INTO machines (id, hostname, serial_number, is_managed, last_heartbeat, os_name) VALUES (?, ?, ?, ?, ?, ?)',
        [id, m.hostname, `SN-${Math.random().toString(36).substring(7).toUpperCase()}`, 1, m.status === 'online' ? new Date().toISOString() : new Date(Date.now() - 86400000).toISOString(), m.os]
      );

      await dbRun('INSERT INTO machine_metadata (machine_id, category, location, description, tags, notes) VALUES (?, ?, ?, ?, ?, ?)',
        [id, m.category, 'Headquarters', `Standard ${m.category} deployment`, JSON.stringify(m.tags), 'Auto-generated by seed script']
      );

      await dbRun('INSERT INTO network_interfaces (id, machine_id, mac_address, ip_address, mapping_source) VALUES (?, ?, ?, ?, ?)',
        [uuidv4(), id, '00:1A:2B:3C:4D:5E', m.ip, 'DHCP']
      );

      // Link some incidents/apps
      if (m.hostname === 'APTIV-LPT-002') {
        await dbRun('INSERT INTO incidents (id, title, description, priority, status, machine_id, created_by) VALUES (?, ?, ?, ?, ?, ?, ?)',
          [uuidv4(), 'Slow Performance', 'User reports system freezing during boot.', 'Low', 'Open', id, adminId]
        );
      }
      console.log(`+ Added machine ${m.hostname}`);
    } else {
      console.log(`~ Machine ${m.hostname} already exists`);
    }
  }

  // Create sample compliance rules
  console.log('Checking compliance rules...');
  const rules = [
    { name: 'Tanium Agent Required', type: 'mandatory', app: 'Tanium', sev: 'critical', desc: 'Tanium endpoint management agent must be installed' },
    { name: 'CrowdStrike Required', type: 'mandatory', app: 'CrowdStrike', sev: 'critical', desc: 'CrowdStrike Falcon sensor must be installed for endpoint protection' },
    { name: 'WinRAR Not Allowed', type: 'blacklist', app: 'WinRAR', sev: 'warning', desc: 'WinRAR is not approved - use 7-Zip instead' },
    { name: 'TeamViewer Not Allowed', type: 'blacklist', app: 'TeamViewer', sev: 'critical', desc: 'Unauthorized remote access software is prohibited' }
  ];

  for (const r of rules) {
    const existing = await dbGet('SELECT id FROM compliance_rules WHERE name = ?', [r.name]);
    if (!existing) {
      await dbRun(
        `INSERT INTO compliance_rules (id, name, rule_type, app_name, severity, description) VALUES (?, ?, ?, ?, ?, ?)`,
        [uuidv4(), r.name, r.type, r.app, r.sev, r.desc]
      );
      console.log(`+ Added rule ${r.name}`);
    } else {
      console.log(`~ Rule ${r.name} already exists`);
    }
  }

  // Create sample news item
  console.log('Checking news items...');

  // Using existing images found in server/uploads/news
  const newsItems = [
    { title: 'Q1 Compliance Report Available', content: 'The Q1 2026 security compliance report has been published. Please review the new guidelines for remote access.', img: '/uploads/news/874085cd-1cef-4891-8176-394bc7564299.jpg' },
    { title: 'New IT Support Portal', content: 'We have launched a new support portal for faster ticket resolution. Access it through the intranet homepage.', img: '/uploads/news/dc6cc9b7-c80f-405a-afd1-34037b9bdc59.jpg' },
    { title: 'Emergency Maintenance', content: 'Server maintenance scheduled for this Saturday. Expect intermittent connectivity between 2AM and 4AM.', img: '/uploads/news/f459759c-e301-4f63-8bb8-5fa3cf1dcd27.png' }
  ];

  for (const n of newsItems) {
    const existing = await dbGet('SELECT id FROM news_items WHERE title = ?', [n.title]);
    if (!existing) {
      await dbRun(
        `INSERT INTO news_items (id, title, content, is_active, sort_order, created_by, image_path) VALUES (?, ?, ?, 1, 0, ?, ?)`,
        [uuidv4(), n.title, n.content, adminId, n.img]
      );
      console.log(`+ Added news ${n.title}`);
    } else {
      console.log(`~ News ${n.title} already exists`);
    }
  }

  closeDatabase();
  console.log('✓ Database seed completed!');
}

seed().catch(console.error);
